- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - ufw
      - fail2ban
    state: present
